## Basic Configuration

baseurl = "https://blitzracingcc.com/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"

author = "Matt Kharrl"
title = "Blitz Racing Club"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Blitz Racing Club"
# intro = "USA Cycling Club"
description = "Blood, sweat, respect. The first two you give, the last one you earn."
authorimage = "blitz_logo.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "blitz,cycling,racing,team,cc"

## About Us
[params.about_us]
about_us_content = "Blitz Racing is a USA Cycling registered and sanctioned club comprising racers and riding enthusiasts dedicated to cycling in all its forms. We ride and race in road, cyclocross, and mountain bike events whenever we can. Blitz Racing was founded in San Antonio, Texas, but has grown to include athletes across the US. The club eats, sleeps, and breathes bike riding!"

## Social Accounts
[params.social]
instagram = "blitzracingcc"
instagram_embed = "blitzracingcc"
facebook = "blitzracingcc"
strava_club = "blitzracing"
facebook_embed = "blitzracingcc"
# github = "<username>"
# linkedin = "<username>"
# twitter = "<username>"
# google = "<username>"
# stackoverflow = "<username>"
# email = "you@example.com"

## Sponsors
[[params.sponsors]]
    name = "roka"
    img = "/img/roka_logo.svg"
    url = "https://www.roka.com/"
[[params.sponsors]]
    name = "pedal haus brewery"
    img = "/img/pedal_haus_logo.png"
    url = "https://www.pedalhausbrewery.com/"
[[params.sponsors]]
    name = "cyclebar stone oak"
    img = "/img/cyclebar_logo.png"
    url = "https://www.cyclebar.com/location/stone-oak"
[[params.sponsors]]
    name = "restore sonterra"
    img = "/img/restore_logo.png"
    url = "https://www.restore.com/locations/tx-san-antonio-sonterra-tx008"
[[params.sponsors]]
    name = "tequila penasco"
    img = "/img/tequila_penasco_logo.png"
    url = "https://www.tequilapenasco.com/"
[[params.sponsors]]
    name = "north park lexus at dominion"
    img = "/img/lexus_logo.png"
    url = "https://www.northparklexusatdominion.com/"
[[params.sponsors]]
    name = "vermeer mountain west"
    img = "/img/vermeer_logo.png"
    url = "https://vermeermountainwest.com/"
[[params.sponsors]]
    name = "the wash tub"
    img = "/img/wash_tub_logo.png"
    url = "https://washtub.com/"
[[params.sponsors]]
    name = "teka molino"
    img = "/img/teka_molino_logo.png"
    url = "https://www.facebook.com/TekaMolino/"
[[params.sponsors]]
    name = "mathew gordon MD DDS"
    img = "/img/mathew_gordon_logo.png"
    url = "https://www.lonestaroms.com/mathew-c-gordon"

## Extras
[params.extra]
copyright = "© 2022. Blitz Racing CC. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = false
hightlightjs = false
displayrssicon = false

## Main Menu
# [[menu.main]]
#     name = "blog"
#     weight = 100
#     identifier = "blog"
#     url = "/blog/"
# [[menu.main]]
#     name = "about"
#     identifier = "about"
#     weight = 200
#     url = "/about/"
# [[menu.main]]
#     name = "coderag"
#     identifier = "coderag"
#     weight = 300
#     url = "/coderag/"
